version: '3.9'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment: 
        ACCEPT_EULA: 'Y'
        SA_PASSWORD: 'NotAll0wedForPublic'
    ports:
    - 8725:1433