@url = https://localhost:7283

### Health check
GET {{url}}/health/users-module

### Sign up user
POST {{url}}/users-module/users/sign-up
Content-Type: application/json

{
    "email": "krystianpetek2@gmail.com",
    "password": "Password!23",
    "role":"admin"
}

### Sign in user
POST {{url}}/users-module/users/sign-in
Content-Type: application/json

{
    "email": "krystianpetek2@gmail.com",
    "password": "Password!23"
}

### Get user info
@token = token
@userId = 5b0930f8-374c-411f-8af7-ac90e71d6013

GET {{url}}/users-module/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}