@url = https://localhost:7283

### Health check
GET {{url}}/health/users-module

### Sign up user
POST {{url}}/users-module/users/sign-up
Content-Type: application/json

{
    "email": "krystianpetek2@gmail.com",
    "password": "Password!23",
    "role":"admin"
}

### Sign in user
POST {{url}}/users-module/users/sign-in
Content-Type: application/json

{
    "email": "krystianpetek2@gmail.com",
    "password": "Password!23"
}

### Auth information
@token = token
@userId = a51543c7-3bef-49d6-8de8-b5a3e945c85d

### Get current logged user info
GET {{url}}/users-module/users/me
Content-Type: application/json
Authorization: Bearer {{token}}

### Get user info
GET {{url}}/users-module/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Sign out user
POST {{url}}/users-module/users/sign-out
Content-Type: application/json
Authorization: Bearer {{token}}

### Deactivate user
POST {{url}}/users-module/users/deactivate
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userId": "{{userId}}"
}