@url = https://localhost:7283

### Health check
GET {{url}}/health/users

### Sign up user
POST {{url}}/users-module/account/sign-up
Content-Type: application/json

{
    "email": "krystianpetek2@gmail.com",
    "password": "Password!23",
    "role":"admin"
}

### Sign in user
POST {{url}}/users-module/account/sign-in
Content-Type: application/json

{
    "email": "krystianpetek2@gmail.com",
    "password": "Password!23"
}